name: Auto-trigger-3hrs

on:
  schedule:
    - cron: "0 */3 * * *"  # Triggers every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger endpoint
        run: |
          curl -X POST https://socialfiagent.onrender.com/post-on-ping
