name: Auto-trigger-vercel

on:
  schedule:
    - cron: "0 */1 * * *"  # Triggers every 1 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger endpoint
        run: |
          curl -X POST https://replyforsocifiagent.onrender.com/
