name: Auto-trigger-vercel

on:
  schedule:
    - cron: "0 */4 * * *"  # Triggers every 3 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger endpoint
        run: |
          curl -X POST https://socialfiagent.vercel.app/post-on-ping
